project:
  type: "website"

website:
  title: "Matt Fisher"
  site-url: "https://mfisher87.github.io/"
  repo-url: &repo-url "https://github.com/mfisher87/mfisher87.github.io"
  repo-actions: ["edit", "issue"]

  navbar:
    right:
      # - text: CV
      #   file: cv.qmd
      - text: "Posts"
        file: "posts/index.md"
      - icon: "github"
        href: "https://github.com/mfisher87"
format:
  html:
    theme: "flatly"
    css: "styles.css"
