project:
  type: "website"

website:
  title: "Matt Fisher"
  site-url: "https://mfisher87.github.io"
  repo-url: &repo-url "https://github.com/mfisher87/mfisher87.github.io"
  repo-subdir: "content"
  repo-actions: ["edit", "issue"]

  navbar:
    right:
      - text: "Blog"
        file: "posts/index.md"
      - text: "Resume"
        file: "resume.pdf"
      - text: "My work"
        menu:
          - text: "Projects"
            href: "my-work/projects/index.md"
          - text: "Talks"
            href: "my-work/talks/index.md"
          - text: "Awards"
            href: "my-work/awards/index.md"
          - text: "Maintenance"
            href: "my-work/maintenance/index.md"
      - text: "More"
        menu:
          - text: "Cognitive load"
            file: "more/cognitive_load.md"
          - text: "Communities"
            file: "more/communities.md"
          - text: "My other sites"
            file: "more/internal_links.md"
          - text: "External links / blogroll"
            file: "more/external_links.md"
          - text: "---"
          - text: "Crows"
            file: "more/crows.md"
          - text: "LEDs"
            file: "more/leds.md"
      - icon: "github"
        aria-label: "GitHub"
        href: "https://github.com/mfisher87"

  page-footer:
    left: "© Matt Fisher 2023"
    right: "Built with [Quarto](https://quarto.org/) ❤️"


format:
  html:
    theme:
      light: ["flatly", "styles.scss"]
      dark: ["darkly", "styles.scss"]
    # Turn on emoji shortcodes:
    from: "markdown+emoji"

    toc: true

# Enable comments by default
# IMPORTANT: Set `comments: false` on pages like indexes!
# TODO: This config is duplicated mostly for blog posts, how to DRY?
comments:
  giscus:
    repo: "mfisher87/mfisher87.github.io"
    repo-id: "R_kgDOIyvIJQ"
    category: "Other pages"
    category-id: "DIC_kwDOIyvIJc4CcIIr"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "top"
    # TODO: In Quarto 1.4, light/dark themes are supported
    # https://github.com/quarto-dev/quarto-cli/issues/4820
    # theme:
    #   light: "preferred_color_scheme"
    #   dark: "noborder_dark"
    theme: "light"
    language: "en"
    loading: "lazy"
