project:
  type: "website"

website:
  title: "Matt Fisher"
  navbar:
    right:
      # - text: CV
      #   file: cv.qmd
      - text: "Posts"
        file: "posts/index.md"
      - icon: "github"
        href: "https://github.com/mfisher87"
format:
  html:
    theme: "flatly"
    css: "styles.css"
