# Automatically create a GitHub Release for every push to the `main` branch
name: "Auto-release (calver) and trigger Zenodo DOI"

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/release.yml"
      - "content/**"

  # Run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: "write"


# Allow one concurrent deployment
concurrency:
  group: "release"
  cancel-in-progress: true


jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: '3.12'
          # TODO: Is using the cache slower than setting up the env fresh
          # each time? It's a small env.
          cache: 'pip'

      - name: "Install bumpver"
        run: "pip install bumpver"

      - name: "Bump version (calver)"
        run: "bumpver update --push"

      - name: "Get new version number"
        id: "get_version"
        run: "bumpver show --no-fetch --environ >> $GITHUB_OUTPUT"

      - name: "Create Release"
        uses: "actions/create-release@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ steps.get_version.outputs.CURRENT_VERSION }}"
          release_name: "${{ steps.get_version.outputs.CURRENT_VERSION }}: Auto-release"
          body: |
            This is an automated release generated by GitHub Actions!
          draft: false
          prerelease: false
